// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzHCK3gRLodb41cqVjrr4Dp47j0uTDUb8',
    appId: '1:972659297586:web:de9c4be17218da35895b2b',
    messagingSenderId: '972659297586',
    projectId: 'fluent-ai-new',
    authDomain: 'fluent-ai-new.firebaseapp.com',
    storageBucket: 'fluent-ai-new.firebasestorage.app',
    measurementId: 'G-QLKQ8GK8VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7h3EJ_Zx_zLsyCOXkzpHiuGBdS2IdCH8',
    appId: '1:972659297586:android:778823a212e8a4ba895b2b',
    messagingSenderId: '972659297586',
    projectId: 'fluent-ai-new',
    storageBucket: 'fluent-ai-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtLfSM8ik6w1NVaxf6zVm0j4yQD47Dam8',
    appId: '1:972659297586:ios:83597631140ad83d895b2b',
    messagingSenderId: '972659297586',
    projectId: 'fluent-ai-new',
    storageBucket: 'fluent-ai-new.firebasestorage.app',
    iosBundleId: 'com.example.fluentAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtLfSM8ik6w1NVaxf6zVm0j4yQD47Dam8',
    appId: '1:972659297586:ios:83597631140ad83d895b2b',
    messagingSenderId: '972659297586',
    projectId: 'fluent-ai-new',
    storageBucket: 'fluent-ai-new.firebasestorage.app',
    iosBundleId: 'com.example.fluentAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzHCK3gRLodb41cqVjrr4Dp47j0uTDUb8',
    appId: '1:972659297586:web:8d86c1229a6cb0e2895b2b',
    messagingSenderId: '972659297586',
    projectId: 'fluent-ai-new',
    authDomain: 'fluent-ai-new.firebaseapp.com',
    storageBucket: 'fluent-ai-new.firebasestorage.app',
    measurementId: 'G-YZ1J8Z9H0E',
  );
}
